### PR TITLE
Remove my password from the list not to let hackers hack me

### PR DESCRIPTION
**Pull request by fgRuslan**

### CODE REVIEW

**Comment by sirjmkitavi** [comment]
Nice, now we know your password... No need to brute force you.
Good Work on trying to be safe.

**Comment by g0tmi1k** [comment]
Oh look... another troll
</shock>
#170, #158, #155 (Bonus round: #159).

Time to `./up-y0ur-game.sh`

**Comment by HCLarsen** [comment]
The first one of these was amusing, but now it's just getting old.

**Comment by fgRuslan** [comment]
Hi guys, I'm writing from the account of this moron. His password was heckfy7399. Bye!

**Pull request closed without merging**
