### PR TITLE
Add other possible types of SSH key files.

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR (fix and replace the PR #745) add other possible types of SSH key files and variations on the extensions:

* identity
* id_dsa
* id_ecdsa
* id_ed25519
* id_ecdsa_sk
* id_ed25519_sk

My sources were the following:

1) The content of the **sshd_config** file:

image

2) The content of the configuration folder of a ssh server **/etc/ssh**:

image

3) The documentation of the **ssh-keygen** tool:

image

Thank you very much in advance 😃 

> **Note**:

In addition, I made a proposal for #760

### CODE REVIEW

**Review by ItsIgnacioPortal — APPROVED** [review]
Looks good! Thanks for contributing 😁

**Comment by righettod** [comment]
You are welcome 😃

**Comment by righettod** [comment]
In parallel, I proposed a fix for #760.

**Comment by ItsIgnacioPortal** [comment]
> In addition, I proposed a fix for #760.

I think that rather than a bash script, we should add a CI check as a Github Action, so that every pull request is audited/fixed automatically.

**Comment by righettod** [comment]
Good idea. The bash script can be used in a CI pipeline to update dicts as
well. I proposed a bash script to have a script to perform this update in a
common way either in one shot or in regular way (like in CI).

**Comment by righettod** [comment]
Will provide a single focused one to made it consistent.

**Comment by righettod** [comment]
Replaced by PR #795

**Comment by righettod** [comment]
> > In addition, I proposed a fix for #760.
> 
> I think that rather than a bash script, we should add a CI check as a Github Action, so that every pull request is audited/fixed automatically.

PR #800 proposed to go in this way 😃

**Pull request closed without merging**
