### PR TITLE
add swagger path

### PR DESCRIPTION
**Pull request by soufianetahiri**

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Source?

**Comment by soufianetahiri** [comment]
> Source?

Devs... I'm a developer and those are default paths

**Comment by g0tmi1k** [comment]
Is there something were you can reference this too?

**Comment by cnotin** [comment]
Possible source: https://github.com/projectdiscovery/nuclei-templates/blob/77e5d112be1e3a2a6ce659d525ed5aedf553ee5b/panels/swagger-panel.yaml

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
