### PR TITLE
Delete all passwords

### PR DESCRIPTION
**Pull request by ycwei982**
So hackers cannot hack anymore. SECURES THE WORLD

### CODE REVIEW

**Comment by mchorse** [comment]
Do hackers even need those passwords? 🤔

**Comment by hinell** [comment]
@mchorse After this PR they surely won't. 😅

**Comment by aisbaa** [comment]
Is it Aprils fools day? :laughing:

**Comment by Jan200101** [comment]
@hang333 why are you so hostile towards this PR?
It will save million accounts from being stolen

**Comment by maxex0000** [comment]
Don't use any password then hackers can't hack your password.

**Pull request closed without merging**
