### PR TITLE
More API endpoints (from assetnote) and sort everything

### PR DESCRIPTION
**Pull request by shelld3v**

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Source?

**Comment by shelld3v** [comment]
wordlist.assetnote.io (I used some scripts to find most valuable endpoints)

**Comment by g0tmi1k** [comment]
Thanks!
Able to share the scripts used too?

**Comment by shelld3v** [comment]
I believe I deleted it, but it's just something like: choose only entries that start with `/api` (some start with `/v1`, `/v2`), remove entries that contain special characters (`-`, `_`, ...), remove entries that are too long, remove entries that have too much `/`, ... I just did several things like that until the result is as small as I want, and when I looked through, the endpoint seemed valuable

**Pull request merged**
