### PR TITLE
[spring-boot.txt] Add new endpoints

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR use this [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.actuator.management.server.base-path) to add the prefix `management/` to endpoints list from this [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints):

image

image

Command used to extract endpoints:

```shell
curl -sk https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/html/production-ready-endpoints.html | grep -Po '<code class="literal">([a-z]+)</code>' | cut -d'>' -f2 | cut -d'<' -f1 | sort -u
```

Thanks in advance 😃

### CODE REVIEW

**Review by ItsIgnacioPortal — APPROVED** [review]

**Comment by ItsIgnacioPortal** [comment]
Good stuff @righettod

**Comment by righettod** [comment]
Thank you very much @ItsIgnacioPortal  👍

**Comment by g0tmi1k** [comment]
Thanks @righettod .
Great suggestion - as all the others <3

_and I love how detailed the pull request is!)

**Comment by righettod** [comment]
Thank you very much ❤️

**Pull request merged**
