### PR TITLE
Update worst-passwords-2017-top100-shadow.txt

### PR DESCRIPTION
**Pull request by sh4d0w-kartik**
@[https://shadow/world.com](https://shadow/world.comhttps://shadow/world.comhttps://shadow/world.com) For updates

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Thanks for the suggestion @sh4d0w-kartik 

The source isn't working for me: `https://shadow/world.com` - could you please double check it?

**Comment by sh4d0w-kartik** [comment]
Sure I'll check it again

**Comment by g0tmi1k** [comment]
@sh4d0w-kartik 
Where did these values come from?

**Comment by g0tmi1k** [comment]
Closing due to lack of response :(

**Pull request closed without merging**
