### PR TITLE
Add humans.txt

### PR DESCRIPTION
**Pull request by fiLLLip**

### CODE REVIEW

**Comment by fiLLLip** [comment]
For reference: http://humanstxt.org/

**Comment by srasku** [comment]
It would be good to include the reference in the actual commit message.  That way you can understand the motivation of the commit without having access to GitHub.

**Comment by fiLLLip** [comment]
@srasku Better? :smiley:

**Comment by srasku** [comment]
Nice!  I don't have write permission on this repo otherwise I would approve.

**Comment by AstroOrbis** [comment]
Seems good

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
