### PR TITLE
feat(Passwords/Books): Add greatest books title list

### PR DESCRIPTION
**Pull request by emmanuel-londono**
- A list of titles from the world's most acclaimed literary works, scraped from [thegreatestbooks.org](https://www.thegreatestbooks.org/)
- 1st list: Each title should have at least one leetspeak version and one version where whitespaces are converted to '_' and another where whitespace is removed
- 2nd list: Each title is displayed normally.
- 3rd list: Each title is lowercased and joined or underscored.
- 4th list: Each title is uppercased and joined or underscored.
- There are no duplicate titles per file.
- Updated size for SecLists should still be about 2.88GB

### CODE REVIEW

**Comment by molangning** [comment]
Great work, but can you add one more variation where the letters are lowercased and there are no spaces? I feel that it will cover more possibilities where the user may have the book name in those variation.

Example:
In Search of Lost Time mutates to `in search of lost time`, `in_search_of_lost_time`, `InSearchofLostTime` and `insearchoflosttime`

Additionally, some titles aren‘t cased properly (e.g. `In Search of Lost Time` becomes `In Search Of Lost Time`) so the mutated versions could have them?

**Comment by emmanuel-londono** [comment]
> Great work, but can you add two more variation where the letters are lowercased and the space removed? I feel that it will cover more possibilities where the user may have the book name in those variation.
> 
> Example: In Search of Lost Time mutates to `in search of lost time`, `in_search_of_lost_time`, `InSearchofLostTime` and `insearchoflosttime`
> 
> Additionally, some titles aren‘t cased properly (e.g. `In Search of Lost Time` becomes `In Search Of Lost Time`) so the mutated versions could have them? `Ulysses` appeared twice in the version with variations too.

Sounds good! I made the changes. (The casing in the original txt file are the titles as they appear officially in the ISBN.)

**Comment by molangning** [comment]
Looks good to me, hope it gets merged

**Comment by g0tmi1k** [comment]
Oh wow! Thanks @emmanuel-londono !

**Pull request merged**
