### PR TITLE
fix(CICD): Corrected multiple issues in GitHub Actions workflows

### PR DESCRIPTION
**Pull request by ItsIgnacioPortal**
This pull request fixes the following bugs 🐛 in the Seclists Github Actions:
- Some wordlists were executing on every single commit instead of only executing when one of the specified paths were modified.
- The `Wordlist Updater - directories` GitHub Action had an incorrect job name.
- The `Wordlist Updater - directories` GitHub Action had trailing whitespaces in the trigger filepaths.
- The workflows `Wordlist Updater - Trickest wordlists updater` and `Readme updater - Updates readme with latest stats` had missing `content: write` permissions, which caused these actions to fail when executed in a Seclists fork with the default [github-actions account security settings](https://stackoverflow.com/a/75308228/11490425).
- The workflows `Wordlist Updater - directories` and `Wordlist Updater - words` had hard-coded repo URLs, which caused the workflow runs to fail whenever they were executed in a fork of Seclists.

### CODE REVIEW

**Comment by molangning** [comment]
Good catch! LGTM

**Comment by ItsIgnacioPortal** [comment]
Added:
- I've replaced the email address `example@github.com` with the email address of the official github-actions bot. See: #1023

**Comment by molangning** [comment]
A commit script might be helpful as we are just copy and pasting commit codes

**Comment by molangning** [comment]
I made a commit script, you can check it out here
https://github.com/molangning/irr-tracker/blob/main/run.sh
https://github.com/molangning/irr-tracker/blob/main/.github/workflows/update.yml

**Comment by g0tmi1k** [comment]
Hi @ItsIgnacioPortal - Oh super wowerz! 

Unfortunately before this can be merged in, could you fix the conflicts?

**Comment by ItsIgnacioPortal** [comment]
> Hi @ItsIgnacioPortal - Oh super wowerz!
> 
> Unfortunately before this can be merged in, could you fix the conflicts?

Conflict fixed 😃

**Comment by g0tmi1k** [comment]
Thanks a lot for this @ItsIgnacioPortal! (Really!)

Merged <3

**Pull request merged**
