### PR TITLE
Added more PHP web shells 

### PR DESCRIPTION
**Pull request by chashtag**
Added more PHP web shells 
Removed spaces from a file name

### CODE REVIEW

**Review by its0x08 — APPROVED** [review]

**Comment by its0x08** [comment]
Always in need for more of this 😁

**Comment by g0tmi1k** [comment]
Is there a source for the PHP shell filenames?

**Comment by g0tmi1k** [comment]
Going to merge without a source

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
