### PR TITLE
ISPSystem BillManager - list of api endpoints for hostings penetration tests

### PR DESCRIPTION
**Pull request by TheQmaks**

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Source?

**Review by its0x08 — APPROVED** [review]

**Comment by TheQmaks** [comment]
> Source?

Parsed by me from that docs page https://docs.ispsystem.com/billmanager/developer-section/billmanager-api

**Comment by TheQmaks** [comment]
So?

**Comment by its0x08** [comment]
Lately things are moving slowly here.

**Comment by g0tmi1k** [comment]
Thanks for the pull request (and sorry for the delay!)

**Pull request merged**
