### PR TITLE
Structure Clean Up (v2) & Issue fixes!

### PR DESCRIPTION
**Pull request by g0tmi1k**
Based upon PR: #128

Updates all PRs since merging: #122, #123, #125, #126, #136, #146, #149, #162, #174, #176

And a few other little bits and bobs.

Fixes various issues too
...yes, I know its a very large PR, but as its a PITA to get anything merged. I figured I would do 'one big one' to try and catch them all, kick starting activity once again for this project.

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Is it possible to get a tag released afterwards?

**Comment by g0tmi1k** [comment]
@danielmiessler // @jhaddix Is it possible to get a tag released afterwards?

**Comment by g0tmi1k** [comment]
🎉 🎈 👍 🥇 💯 😄

**Comment by codingo** [comment]
Heck of a lot of work here @g0tmi1k - thank-you for the awesome effort!

**Comment by jhaddix** [comment]
Absolutely. Thanks @g0tmi1k !!!

**Pull request merged**
