### PR TITLE
openapi.json to Swagger and Api-endpoints lists

### PR DESCRIPTION
**Pull request by legik**
Added openapi.json to Swagger and Api endpoint lists

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Thanks for the suggestion @legik 

Do you have a source/reference of why its added?

**Comment by legik** [comment]
According to the OpenAPI Specification (https://swagger.io/specification/)
`It is RECOMMENDED that the root OpenAPI document be named: openapi.json or openapi.yaml`

I was considering including this in the API and Swagger lists.

**Comment by legik** [comment]
hi @g0tmi1k , any updates?

**Comment by g0tmi1k** [comment]
Thanks @legik !

**Pull request merged**
