### PR TITLE
fuzz-b00m-friendly.txt: remove two keywords spotted by WAF

### PR DESCRIPTION
**Pull request by cosad3s**
(Path Traversal attempts I suppose)

### CODE REVIEW

**Comment by cosad3s** [comment]
Yes : it was a WAF provided by Akamai :)

**Comment by molangning** [comment]
looks like the file triggered the check, can you please remove the last new line?

**Comment by g0tmi1k** [comment]
This may be worth reporting upstream ~ https://github.com/Bo0oM/fuzz.txt/blob/master/fuzz.txt

**Comment by g0tmi1k** [comment]
Ah! Following on from db6c2860859fc6da13e954d00cb89ef10d1f4776

`Fuzzing/fuzz-Bo0oM-friendly.txt` is meant for `fuzz-Bo0oM.txt: "WAF friendly" version`.

Cool

**Comment by g0tmi1k** [comment]
Thanks @cosad3s

**Pull request merged**
