### PR TITLE
adding learning materials

### PR DESCRIPTION
**Pull request by ZonkSec**
I thought it would be interesting and useful to have some lists for people who want to learn more about information security or sharpen their skills. So far, I created two lists: one for free training and another for practice sites.

### CODE REVIEW

**Comment by awhitehatter** [comment]
I love this idea, if you move forward with this idea, might I suggested that files be written in markdown. So links and the like work?

**Comment by whoot** [comment]
Good idea. 
However, I think this is not the purpose of SecLists, which "is a collection of multiple types of lists used **during security assessments**."

**Comment by ZonkSec** [comment]
@whoot i see where you are coming from and you make a valid point. this may not be as fitting as i once thought.

**Comment by adamdecaf** [comment]
I like the addition of these links. Perhaps they would be less of an obstruction under a `Learn.md` file instead of a new folder?

**Comment by danielmiessler** [comment]
Hey guys, thanks so much for this, but I think they might be better suited for the Awesome Lists project for Infosec. Have you seen that one?

**Pull request closed without merging**
