### PR TITLE
Update ftp-betterdefaultpasslist.txt

### PR DESCRIPTION
**Pull request by IndiNijhof**
Added anonymous login credentials for more complete enumeration

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Thank you!

**Comment by IndiNijhof** [comment]
Hi,

I'm so sorry to bother you, but I've made a rather stupid mistake. I
committed the change before setting my github email settings to private.
Causing my private email address to show up on the commit patch file.

Would there be any way for you to remove this or delete the commit from the
history? I can then submit a new pull request.

Again, so sorry to bother you with this. I hope you can help me.

Thanks,

Indi Nijhof

**Comment by g0tmi1k** [comment]
Hello @IndiNijhof ,

I'm sorry to say, but there isn't a nice way of doing this, as it will require a force push to the master branch.
This means any forks or clones would break.

Is it really that big of a deal?

**Comment by IndiNijhof** [comment]
Hi g0tmi1k,

I don't believe it to be such an issue as to warrant such a destructive
change, but thanks anyway for replying!

By the way, your articles and posts regarding pentesting are awesome and
really helpful :)

With kind regards,

Indi



Op zo 10 feb. 2019 om 20:40 schreef g0tmi1k <notifications@github.com>:

**Comment by g0tmi1k** [comment]
Thanks for being understanding!
And you're welcome =)

**Pull request merged**
