### PR TITLE
Create top-apk-params.txt

### PR DESCRIPTION
**Pull request by J-GainSec**
Parameters from the Top 55 Android applications.

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
How did you get these parameters? are they URL parameters?

**Comment by J-GainSec** [comment]
I downloaded the top 55 mobile apps and extracted relative links/parameters from each file in the apk and made a pretty awesome API wordlist. - Nullenc0de

https://gist.github.com/nullenc0de/e9d1f2a8a0a38c9bfcb5bdb9fc7191ea

https://twitter.com/nullenc0de/status/1425973675715612672

**Comment by ItsIgnacioPortal** [comment]
Great! Could you also add https://gist.github.com/nullenc0de/e9d1f2a8a0a38c9bfcb5bdb9fc7191ea, since they were both announced in the same tweet. Just make sure to remove the trailing `/`

**Comment by J-GainSec** [comment]
Done, adding the other file now.

**Comment by g0tmi1k** [comment]
Semi related ~ https://github.com/danielmiessler/SecLists/pull/786

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
