### PR TITLE
Create 1-4_all_letters_a-z.txt

### PR DESCRIPTION
**Pull request by parthmalhotra**
For bruteforcing

### CODE REVIEW

**Comment by g0tmi1k** [comment]
When would this be useful?

**Comment by parthmalhotra** [comment]
Found it useful several times. Can  be used for bruteforcing files/api endpoints. Also for the same reason for which we use 4-digits-0000-9999.txt :)

**Comment by g0tmi1k** [comment]
Thanks!

**Comment by parthmalhotra** [comment]
Sometimes developers tend to create random files/folders (i.e dfuh.php which maybe list's db contents), I use this list when i am done bruteforcing with my default list and sometimes it have given very good results :) Btw big fan of you @g0tmi1k

**Pull request merged**
