### PR TITLE
added 'fully-qualified-java-classes' to fuzzing lists

### PR DESCRIPTION
**Pull request by jorelpaddick**
A list of fully-qualified Java classes is useful for fuzzing Java applications. 

For example, some applications accept these class names as parameters in an HTTP request. The list may help discover deserialisation, type confusion or other bugs related to the processing of these Java object types.

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
This Pull Request has now been merged in [Seclists-Express](https://github.com/ItsIgnacioPortal/SecLists-Express)!
Seclists-Express is a frequently-updated fork of Seclists.

Thank you for contributing 💚

**Comment by g0tmi1k** [comment]
Nice suggestion @jorelpaddick ! I like it.

Do you have a source at all?

**Comment by jorelpaddick** [comment]
Sure! The source for the list https://docs.oracle.com/javase/8/docs/api/
It was curated by me: jorelpaddick/fully-qualified-java-classes

**Comment by g0tmi1k** [comment]
Thanks @jorelpaddick <3

**Pull request merged**
