### PR TITLE
Create country-codes.txt

### PR DESCRIPTION
**Pull request by D3vil0per**
According to the ISO 3166-1 standard. Useful for fuzzing elements like usernames as 'support-us' 'admin.us' 'helpdesk-US' and so on.

### CODE REVIEW

**Comment by D3vil0per** [comment]
> Is there a link to ISO 3166-1 for the source?

Yes @g0tmi1k , you can refer to the official ISO website: https://www.iso.org/obp/ui/#search (ps: sort the elements by Alpha-2 code column).

This link is contained in the wiki page: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements at the reference [1].

I just updated the file with codes in uppercase letters.

**Review by its0x08 — APPROVED** [review]

**Comment by D3vil0per** [comment]
Hello @ItsIgnacioPortal Is there the chance to approve this pull request?

**Review by ItsIgnacioPortal — APPROVED** [review]

**Comment by D3vil0per** [comment]
> > Hello @ItsIgnacioPortal Is there the chance to approve this pull request?
> 
> Done. Thanks for contributing :)

Thanks @ItsIgnacioPortal Is it possible also to merge this pull request? So we can have this file in the SecLists and I can close the pull request.

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
