### PR TITLE
Add path to a common ManageEngine endpoint

### PR DESCRIPTION
**Pull request by righettod**
Hello,

This PR add a path to a endpoint often exposed to anonymous users by [ManageEngine products](https://www.manageengine.com).

Its allow to identify the product name/version, OS and other internals information:

note

Thank you very much in advance 😃

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Source?

**Comment by righettod** [comment]
It's based on the different [issues](https://righettod.eu/#4-vulns) that I have found on these products accross several years.

**Comment by g0tmi1k** [comment]
Works for me, thanks!

**Comment by righettod** [comment]
Thanks a lot for the merging.

**Pull request merged**
