### PR TITLE
Create forefront-identity-management

### PR DESCRIPTION
**Pull request by J-GainSec**
Sourced from https://raw.githubusercontent.com/GainSec/TreeHouse-Wordlists/master/Microsoft-Forefront-Identity-Management-2010.txt

Wordlist for Microsoft Forefront Identity Management 2010

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
What could this wordlist be used for? If its for detecting a "Microsoft Forefront Identity Management 2010" instance, it’s too long

Also how did you make this wordlist?

**Comment by J-GainSec** [comment]
It's for enumerating what files/functionality are being used to discover the attack surface of a Microsoft FIM instance. For example, determining access controls of each user, the xml files within /config/* may contain sensitive data. Depending on what type of smart-card is being used some of the aspx files may or may not be referenced but that doesn't mean they don't exist or aren't accessible. 

From testing a Microsoft FIM instance.

**Review by ItsIgnacioPortal — APPROVED** [review]

**Comment by 1989shack** [comment]
Create a frontend and backend integrated platform

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
