### PR TITLE
add **swagger-ui/ path (springfox)

### PR DESCRIPTION
**Pull request by blaiddx64**
the /swagger-ui path from springfox implementation needs a final slash to be valid as referenced in [this thread](https://github.com/springfox/springfox/issues/3362#issuecomment-719617233)

### CODE REVIEW

**Comment by yash22586** [comment]
That's wrong solve thi fix

**Review by ItsIgnacioPortal — CHANGES_REQUESTED** [review]
Nice! Could you also remove the old entries that don't have a slash? So we can avoid duplicates

**Comment by blaiddx64** [comment]
> Nice! Could you also remove the old entries that don't have a slash? So we can avoid duplicates

done

**Review by ItsIgnacioPortal — APPROVED** [review]

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
