### PR TITLE
Secure password list

### PR DESCRIPTION
**Pull request by sirx**
so everyone will be safe in the webs

### CODE REVIEW

**Comment by ycwei982** [comment]
Why don't remove the whole `./Passwords` so hackers cannot get passwords

**Comment by m1guelpf** [comment]
@sirx You're missing `hounter2` and `correct horse battery staple`

**Comment by sirx** [comment]
Done, shame on me that I forgot those

**Comment by danielmiessler** [comment]
Very cool, but I don't think anyone will actually use them!

**Pull request closed without merging**
