### PR TITLE
Removed comment that causes false positive

### PR DESCRIPTION
**Pull request by yechielw**

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
I don't think the comment should be removed, as it's very helpful. I think it should be the user's job to ensure that comments are ignored in their wordlists

**Comment by g0tmi1k** [comment]
I do find it odd that the comment is that lower down in the file (unless it relates to the line directly under it - if so, its not clear . I would also suspect it applies to other lines as well).

I would then opt for it to be moved to the start of the file OR put into `README.md` (or both ;))

**Comment by g0tmi1k** [comment]
@yechielw are you able to update the pull request?

**Comment by g0tmi1k** [comment]
Please could this MR be fixed up?

**Comment by g0tmi1k** [comment]
Closing due to lack of response :(

**Pull request closed without merging**
