### PR TITLE
Add Trickest wordlists

### PR DESCRIPTION
**Pull request by mhmdiaa**
### Inventory subdomains
This wordlist is based on the subdomains dataset of ~70 public bug bounty programs collected on [Inventory](https://github.com/trickest/inventory).

### Robots
This one contains the raw data of 100, 1000, and 10000 websites' `robots.txt` files. [^1]

### Technologies
These wordlists are based on the source code of the technologies listed [here](https://github.com/trickest/wordlists/blob/main/technology-repositories.json). 

There are two versions of each wordlist:
- Base
Lists the full paths of each file in the repository
```
webapps/examples/WEB-INF/classes/websocket/echo/servers.json
```

- All levels
Includes all directory levels of the files in the base wordlist. This wordlist will be larger than the base wordlist, but it accounts for cases where the directory structure of the repository isn't mapped perfectly on the target.
```
webapps/examples/WEB-INF/classes/websocket/echo/servers.json
examples/WEB-INF/classes/websocket/echo/servers.json
WEB-INF/classes/websocket/echo/servers.json
websocket/echo/servers.json
echo/servers.json
servers.json
```

---

The wordlists are sourced from [trickest/wordlists](https://github.com/trickest/wordlists).

[^1]: Credit to the [RobotsDisallowed](https://github.com/danielmiessler/RobotsDisallowed) and RAFT projects for the original concept.

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
Nice addition! But could you rename the files so they have more descriptive names? It should be immediately obvious what a wordlist is for just by looking at its filename, otherwise this repo becomes a mess very quickly

**Review by ItsIgnacioPortal — APPROVED** [review]
Ah that's much better! Thanks for contributing 😁

**Comment by mhmdiaa** [comment]
All set, @ItsIgnacioPortal 🙂

**Comment by Meuau8274** [comment]
whats a worldless file please help

**Comment by ItsIgnacioPortal** [comment]
> whats a worldless file please help

This isn't google

**Pull request merged**
