### PR TITLE
Fuzz amounts, quantities, or any other numerical values.

### PR DESCRIPTION
**Pull request by ivan-sincek**
Pre-generated wordlists based on [Common Security Issues in Financially-Oriented Web Applications](https://research.nccgroup.com/wp-content/uploads/2020/07/common_security_issues_in_financially-orientated_web.pdf) PDF.

Created to fuzz amounts, quantities, or any other numerical values.

Bypass minimum and maximum restrictions, cause unintended behavior and errors, etc.

Tool to create such wordlists can be found at [ivan-sincek/amounts](https://github.com/ivan-sincek/amounts). Feel free to create and add more wordlists on your own. Works with integer and float numerical values.

### CODE REVIEW

**Comment by ivan-sincek** [comment]
These 4 commits should now be final. Had some minor tweaks, and added few more wordlists since the size is not big at all.

**Comment by ItsIgnacioPortal** [comment]
Sick! But could you add a README.md with a small summary of what those lists are for? You could just copy-paste what you wrote for this PR

**Comment by ivan-sincek** [comment]
Hi,

Done. Kindly let me know if there is anything else I can do.

**Review by ItsIgnacioPortal — APPROVED** [review]

**Comment by g0tmi1k** [comment]
Nice idea!

Thank you

**Pull request merged**
