### PR TITLE
Adding nextcloud & owncloud to common.txt

### PR DESCRIPTION
**Pull request by clem9669**
Hey 🙂 

Nextcloud & ownCloud are two famous software for creating and using file hosting service.

PS: this adding might also be done on bigger discovery list because none of big list contains them

### CODE REVIEW

**Comment by drwetter** [comment]
just my 2c : https://blog.domenic.me/hacktoberfest/

**Comment by clem9669** [comment]
lol.
Sometimes you don't want to miss exposed instances of nextcloud, that's all.
Ich bin kein bot.

**Comment by Skyr** [comment]
> Ich bin kein bot.

That's what all bots say 🤖 😉

**Comment by g0tmi1k** [comment]
Source?

**Comment by clem9669** [comment]
I guess sources are the website editor of the solutions: https://owncloud.com & https://nextcloud.com.

These soft are very famous for self hosting but none is in any wordlist.

For more about the subject of self hosting and how popular are those, i recommande to give a glance at https://trends.google.com/trends/explore?date=today%205-y&q=ownCloud,Nextcloud,Seafile,Pydio

Cheers 🙂

**Comment by g0tmi1k** [comment]
But where on those pages does it give those URLs?

**Comment by clem9669** [comment]
Not sure to understand the question here. It is a software and most of people with deploy their website like http://URL/nextcloud or http://URL/owncloud. 
It behaves as you would expect (example: a webmail software like http://URL/webmail), same here. 

First result on google for **deploy nextcloud**: https://help.dreamhost.com/hc/en-us/articles/235545207-Step-by-step-guide-to-deploy-Nextcloud-on-DreamCompute => deploy to http://URL/nextcloud
Variante existe where it is used as subdomain.

I don't know how to explain more. It is just a very good ressource to find deployed ressources on engagement/pentesting. It should be in all basic discovery wordlists.

**Comment by g0tmi1k** [comment]
`https://help.dreamhost.com/hc/en-us/articles/235545207-Step-by-step-guide-to-deploy-Nextcloud-on-DreamCompute` works ;)

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
