### PR TITLE
Add 4D interesting endpoints

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR add some endpoints that can disclose the usage of the [4D technology](https://us.4d.com/).

🌎 Source used: https://doc.4d.com/4Dv18/4D/18.4/Information-about-the-Web-Site.300-5232828.en.html

💻 Example:

image

Thanks in advance 😃

### CODE REVIEW

**Comment by righettod** [comment]
I removed the last empty line but the validator persist to fail ❓ 

image

**Comment by molangning** [comment]
did you collect then by scraping?

**Comment by righettod** [comment]
No, I obtained them from the documentation specified.

**Comment by molangning** [comment]
oh ok

**Pull request merged**
