### PR TITLE
Add endpoint to detect DNS over HTTP supports.

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR add the endpoint exposed when the target supports DNS over HTTP requests.

📖My sources were the following ones:

* https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/miscellaneous/detect-dns-over-https.yaml

👀If the target supports DNS over HTTP then, the behavior should be the following to an HTTP **GET** (the **HTTP 400** is normal because the `accept` request header to `application/dns-json` is missing) :

image

👀Otherwise an HTTP 404 should be obtained:

image

😉Thanks in advance.

### CODE REVIEW

**Review by ItsIgnacioPortal — APPROVED** [review]
LGTM!

**Comment by g0tmi1k** [comment]
Hey @righettod 

Thanks for the suggestion, however unfortunately before this can be merged in, would you be able to fix the conflicts?

**Comment by righettod** [comment]
> Hey @righettod
> 
> Thanks for the suggestion, however unfortunately before this can be merged in, would you be able to fix the conflicts?

Done 😃

**Comment by g0tmi1k** [comment]
Thanks (as always) @righettod 

Merged!

**Pull request merged**
