### PR TITLE
Seclists now available as a snap package.

### PR DESCRIPTION
**Pull request by JitPatro**
You can also embed this Snapstore button if you want to:-

[Get it from the Snap Store](https://snapcraft.io/seclists)

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
Nice! But the links section should have a link to this github reposiory, not a "Developer website" link that just goes to your github profile 👀

**Comment by JitPatro** [comment]
Fixed!

**Review by ItsIgnacioPortal — APPROVED** [review]
Awesome!

**Comment by JitPatro** [comment]
I've the option to add a featured banner. If you can give me a picture with that size restrictions it'll help in popularizing seclists.

image

**Comment by ItsIgnacioPortal** [comment]
This ought to be good enough, unless @danielmiessler can provide a better image

mod1

**Comment by JitPatro** [comment]
It needs to be *exactly* 3:1

image

**Comment by ItsIgnacioPortal** [comment]
Alright, this one has **one pixel less of width** (3999 x 1333). lol
mod1_aaa

**Comment by JitPatro** [comment]
Lol

image

**Pull request closed without merging**
