### PR TITLE
Create sharepoint.txt

### PR DESCRIPTION
**Pull request by J-GainSec**
Sourced from https://github.com/GainSec/TreeHouse-Wordlists/blob/master/Microsoft%20SharePoint.txt

A Microsoft Sharepoint wordlist

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
What could this wordlist be used for? If its for detecting a SharePoint instance, it’s too long

Also how did you make this wordlist?

**Comment by J-GainSec** [comment]
It's for enumerating what files/functionality are being used to discover the attack surface of a SharePoint instance. 

From testing SharePoint instances.

**Comment by J-GainSec** [comment]
https://the-infosec.com/2017/04/18/penetration-testing-sharepoint/

**Comment by ItsIgnacioPortal** [comment]
I see. Alright, now all that's left to do is fix those duplicate slashes.

Also, please rename the wordlist to `sharepoint-ennumeration.txt`. Always use long, descriptive names, if possible.

**Comment by J-GainSec** [comment]
Done!

**Review by ItsIgnacioPortal — APPROVED** [review]
Thanks for contributing 😁

**Review by ItsIgnacioPortal — APPROVED** [review]

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
