### PR TITLE
Create LFI-gracefulsecurity-linux.txt

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Source?

**Comment by noraj** [comment]
https://gracefulsecurity.com/path-traversal-cheat-sheet-linux/

**Comment by v1psta** [comment]
Thanks for that link Alexandre, was looking for it hardcore.
ᐧ

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by g0tmi1k** [comment]
Thank you! 🎉

**Pull request merged**
