### PR TITLE
Add AWS CodeDeploy appspec.yml file to quickhits.txt

### PR DESCRIPTION
**Pull request by tomcodes**

### CODE REVIEW

**Comment by tomcodes** [comment]
**appspec.yml** file can potentially lead to utility scripts that might revela interesting paths / behavior:

https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html

**Comment by g0tmi1k** [comment]
Thank you!

**Comment by tomcodes** [comment]
Thanks for the ultra-quick merge! More to come soon ;)

**Comment by g0tmi1k** [comment]
Looking forward to it ;)
May not be as quick next time(s!)

**Pull request merged**
