### PR TITLE
Update raft-large-words.txt from App-payment

### PR DESCRIPTION
**Pull request by ctflearner**

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
Hello @ctflearner. What is the source for all of these PRs you've made? PR #1076, #1077, #1078, #1079, #1080, #1081 and #1082?

**Comment by ctflearner** [comment]
@ItsIgnacioPortal  Well all the contribution  are taken from my personal projects and some are self made.

**Comment by ctflearner** [comment]
@ItsIgnacioPortal  any update on this ???

**Comment by ItsIgnacioPortal** [comment]
You seem to have made multiple pull requests, many of them with the same contributions, adding content to the same files:
- common.txt
- raft wordlists

For your modifications to `common.txt`, I was able to verify 4/5 of your contributions. I could not find any evidence of `approve_for_claim` being used in the wild. See: https://www.google.com/search?q=%22approve_for_claim%22&nfpr=1
I've unified the verified contributions into a single PR, #1086, where I added you as a Co-Author.

For your modifications to the raft-* wordlists, they'll need to be manually verified and sorted in order to be added into the project. From the 7 scattered PRs you've made, I gathered this list of contributions:
```
account-head
ag-report
amp
AppzillonAdmin
case-assignment
cdt-inclusion
company-profile
cuj
deviation-case-assignment
document-type
edit_account.php
❌ epgdabanew
❌ FnCWeb
loan-dashboard
❌ loan-noc-list
loan-report
loan-settlement
mggc
party-pack
payment-history
role-wise-menu
salesForce-API
serclive
user-wise-menu
view-pao-validated-list
```

The lines that begin with `❌ ` were not found to be in-use in the web. If you have any specific source for those lines, please share it here.

The rest of the contributions seem to be a mix of usernames: `AppzillonAdmin`, URL parameters: `document-type`, filenames: `edit_account.php`, and directories. It would not be useful to seclists users to have such a variety of mixed content in a single file. Please describe what each of those lines is/what each of those lines could be used for so that they can be properly added into their corresponding wordlists.

**Comment by ctflearner** [comment]
@ItsIgnacioPortal Ok I am Closing all the Pull Request so that you can update the wordlist in a more structure way.

**Pull request closed without merging**
