### PR TITLE
added new backupfiles in wordpress fuzz list

### PR DESCRIPTION
**Pull request by abhishekmorla**
credits to : https://www.linkedin.com/feed/update/urn:li:activity:6979486318774923264/

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
This needs to be cleaned up. `wordpress.fuzz.txt` is for fuzzing wordpress. Paths such as ".vscode" and ".viminfo" have nothing to do with wordpress, so they should be in a different wordlist. a general fuzzing wordlist.

**Comment by abhishekmorla** [comment]
.viminfo stores the command line history which can be beneficial in the initial enumeration of the site.
if it's about CTFs then .vscode can also contain juicy information for the next flag.

shall I add these paths in the general wordlist and remove them from WordPress list?

**Comment by ItsIgnacioPortal** [comment]
All of the following files are either already in this repository but in another wordlist, AND/OR have nothing to do wordpress:
- .viminfo
- .vscode
- cgi-bin
- .htaccess
- config.codekit

As for the rest, I think it makes sense adding them:
- dup-installer-bootlog
- wp-snapshots
- installer-backup.php
- installer.php
- wordfence-waf.php

Expect for these; What's the context behind license._**tet**_, and **i.php**?

**Comment by ItsIgnacioPortal** [comment]
@g0tmi1k this pull request wasn't ready for merging. Please read my previous comment here.

**Comment by ItsIgnacioPortal** [comment]
@g0tmi1k this pull request wasn't ready for merging. Please read my previous comment here.

**Pull request merged**
