### PR TITLE
Add: Top common Indian forenames

### PR DESCRIPTION
**Pull request by RAOexe**
Top thousand Indian male and female forenames/firstnames in India

### CODE REVIEW

**Comment by PinkDev1** [comment]
How would this be used? seems useless to me tbh

**Comment by Sandesh333333** [comment]
All Indian people are usd it

**Comment by RAOexe** [comment]
It could be used by Indians as well as neighbouring country's too!

**Comment by PinkDev1** [comment]
@RAOexe used by Indians _for what_?
Give me one realistic example of how this could possibly be used

**Comment by RAOexe** [comment]
@PinkDev1 isn't obivious that it's gonna be used for testing!!!
for example guess the credintials on some website or services...

**Comment by ignoramous** [comment]
Indian here. Can confirm that most use their names, spouse name, children's names as passwords with possibly a few numerals at the begining or the end. Sometimes birth years (yyyy) or dates (ddmmyy).

**Comment by g0tmi1k** [comment]
Whats the source of the names?

**Comment by RAOexe** [comment]
> Whats the source of the names?

What do you mean by source?

**Comment by elitejake** [comment]
Basically, where did you get this wordlist? If you compiled this yourself, where did you source the data?

**Comment by RAOexe** [comment]
I didn't compiled it by myself...
I searched on internet and collected the data, not just from one source but multiple.
Unfortunately I don't remember the sources 🤧

**Comment by g0tmi1k** [comment]
Shame, like to try and give credit where its due =(

**Comment by g0tmi1k** [comment]
Thanks for the PR!

**Review by Sandesh333333 — APPROVED** [review]

**Comment by RAOexe** [comment]
> Shame, like to try and give credit where its due =(

Sorry!
This was my first PR and I'm new in this. Surely will improve from onwards. Thanks for merging!

**Pull request merged**
