### PR TITLE
Create iis-systemweb.txt

### PR DESCRIPTION
**Pull request by J-GainSec**
Sourced from https://github.com/GainSec/TreeHouse-Wordlists/blob/master/IIS_Systemweb_fuzz-WL.txt

A IIS /system_web/ wordlist.

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
What would be the purpose of this wordlist? Why would you want to fuzz that ISS folder?

**Comment by J-GainSec** [comment]
There can be CGIs or other scripts accessible in the /aspnet_client/system_web/* directories even if the ladder two directories are inaccessible . I've encountered CKEditor being there before off the top of my head. 

It's useful to help with discovery when the IIS instance is vulnerable to tilde enumeration since it only discloses a short bit of the directory:

https://github.com/irsdl/IIS-ShortName-Scanner

Also most IIS instances redirect when not including a trailing slash so you can enumerate which numbered directories exist via this wordlist using that as well.

**Comment by ItsIgnacioPortal** [comment]
> There can be CGIs 

Do you mean "CGI" as in Common Gateway Interface?

**Comment by J-GainSec** [comment]
Yes

https://docs.microsoft.com/en-us/iis/configuration/system.webserver/cgi

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
