### PR TITLE
Added actuator default paths and created new XSS fuzzing list

### PR DESCRIPTION
**Pull request by soufianetahiri**
Added actuator paths

### CODE REVIEW

**Comment by soufianetahiri** [comment]
actuator source: https://docs.spring.io/spring-boot/docs/1.5.x/reference/html/production-ready-endpoints.html
XSS source: Payloads I used or I managed to pick up over my pentest journey

**Comment by g0tmi1k** [comment]
Source?

**Comment by soufianetahiri** [comment]
Source are in the first comment

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
