### PR TITLE
new secret keywords added

### PR DESCRIPTION
**Pull request by nsonaniya2010**

### CODE REVIEW

**Comment by nsonaniya2010** [comment]
There is source for these keywords, this keywords are used in my tool to search for secrets:
```
https://github.com/nsonaniya2010/SubDomainizer/blob/master/SubDomainizer.py#L174
```
Here.

**Comment by g0tmi1k** [comment]
Thank you

**Comment by nsonaniya2010** [comment]
can you change the last line :
```
xoxrprivate-key
```
 to 
```
xoxr
private-key
```

**Comment by g0tmi1k** [comment]
Done

**Comment by nsonaniya2010** [comment]
thanks

**Pull request merged**
