### PR TITLE
Add API objects.

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR add the following entries as API objects:
* `server`
* `status`

I often meet them using API discovery operations.

Thanks in advance 😃

### CODE REVIEW

**Comment by righettod** [comment]
I checked th error:
image

🤔There is not 100 lines in the file:
image

**Comment by molangning** [comment]
It might be a bug in the checker, I will look into it soon

**Comment by g0tmi1k** [comment]
Thanks @righettod  - Im not gonna ask for a source on this one ;)

**Comment by righettod** [comment]
I often seen such value when assessing projects using under the hood (not direct exposure):
* Spring boot actuator: https://docs.spring.io/spring-boot/reference/actuator/endpoints.html
* Jax-RS: https://docs.oracle.com/cd/E19798-01/821-1841/6nmq2cp1v/index.html

Hope this clarify the source 😃

**Pull request merged**
