### PR TITLE
Add new Swagger UI path

### PR DESCRIPTION
**Pull request by dee-see**
Just stumbled upon that URL, search `inurl:swagger/ui/index` for examples.

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Source?

**Comment by dee-see** [comment]
Not sure what you're looking for exactly @g0tmi1k, but if you use the dork above you'll find examples where that URL shows Swagger UI pages

https://comtrade.un.org/api/swagger/ui/index
http://service.suedtirol.info/swagger/ui/index
https://sproom.net/swagger/ui/index

I personally stumbled upon it when I used another common swagger UI path on a website and was redirected to that path instead.

**Comment by g0tmi1k** [comment]
Just what I was looking for - thanks!

Unfortunately, there is now a merge conflict - could you fix it up?

**Comment by dee-see** [comment]
I resolved the conflict add prepended a `/` to the other paths to be consistent with the existing path

**Comment by g0tmi1k** [comment]
Thank you! 🎉

**Pull request merged**
