### PR TITLE
Add mostsecure.pw most secure password

### PR DESCRIPTION
**Pull request by grandemk**
Test the most secure password of the world.
Please use this list carefully as using it might change the most secure password of the world and I don't want to update it all the time.

See https://mostsecure.pw

### CODE REVIEW

**Comment by grandemk** [comment]
Love this thread to be honest :)

Made me laugh when I realized the website only ever give one password. Would have been better if it had been dolphin. Might be a subject for a petition.

(Disclaimer: that's not my website or anything)

**Comment by g0tmi1k** [comment]
Could I suggest, if you are going to add it, in the filename, add in the source?
`Passwords/mostsecure.pw.txt`

**Comment by danielmiessler** [comment]
Agree with g0tmi1lk. Some context would be great. Cool idea though!

**Comment by danielmiessler** [comment]
We're going to close this one based on no response, but feel free to re-submit! Thanks!

**Pull request closed without merging**
