### PR TITLE
add localized wikipedia wordlists (Relates to #703)

### PR DESCRIPTION
**Pull request by DeveloperOl**
This pull contains 6 wordlists crawled from wikipedia ordered by word occurrence and limited to 1m words.

de - German
en - English
es - Spanish
fr - French
pt - Portuguese
tr - Turkish

Open for discussion

### CODE REVIEW

**Comment by DeveloperOl** [comment]
Relates to https://github.com/danielmiessler/SecLists/issues/703
@ItsIgnacioPortal

**Comment by ItsIgnacioPortal** [comment]
This has a lot of potential uses, but there seem to be some issues. In the spanish wordlist one of the most used words seems to be "The", but that's not a spanish word. How were these wordlists generated?

**Comment by g0tmi1k** [comment]
Thanks for the work gone into this

is any of the scripts/filters you have created public?
That way we can give credit where its possible :)

**Comment by DeveloperOl** [comment]
The script I wrote is not well documented, but I will work on a Readme - it's just a small python script for processing ZIM files in the same directory. Output is a complete text wordlist and an Sqlite database for manual investigation.
You can find it here: https://github.com/DeveloperOl/wikipediator_v2

**Comment by g0tmi1k** [comment]
Thank you @DeveloperOl

**Pull request merged**
