### PR TITLE
Additional password lists

### PR DESCRIPTION
**Pull request by mcjon3z**
PR containing all of the password lists I have that did not appear to already be in here. I did separate commits for each just in case you wanted to cherry pick or if I accidentally duplicated something.

### CODE REVIEW

**Comment by jabbink** [comment]
:+1:

**Comment by AgelxNash** [comment]
:unlock: Great job!

**Comment by vipuncle** [comment]
Спасибо! :)

**Comment by danielmiessler** [comment]
Thanks so much, man!

**Comment by mcjon3z** [comment]
Oh, forgot to mention - I did not merge any of these lists with the large combined lists. I assumed that was something that you guys did upon approval and merging of the PR...

**Pull request merged**
