### PR TITLE
feat(docs): Improved the CONTRIBUTING.md and the PR template.

### PR DESCRIPTION
**Pull request by ItsIgnacioPortal**
I've added some general advice for writing README entries when making a pull request. This also adds a note to the github PR template highlighting the importance of checking the CONTRIBUTING.md file before creating a pull request.

I think we should remove this line from the CONTRIBUTING.md file. In more recent years Daniel Miessler and Jhaddix seem have have largely disengaged from the project, and may no longer have the time and availability they initially had when they wrote this line: https://github.com/ItsIgnacioPortal/SecLists/blob/8b82f74ee9768cd5f7ea5a54797112f0a2d27c9d/CONTRIBUTING.md?plain=1#L7

> * Email `daniel.miessler@owasp.org` or `jason.haddix@owasp.org` with content to add

@g0tmi1k thoughts?

### CODE REVIEW

**Comment by molangning** [comment]
Looks good, but what is up with `web-extensions-big.txt` being changed?

**Comment by ItsIgnacioPortal** [comment]
That's an automatically generated revert commit, accounting for the commit I did at #999

**Comment by molangning** [comment]
LGTM

**Review by molangning — APPROVED** [review]

**Comment by ItsIgnacioPortal** [comment]
> @g0tmi1k Are you familiar with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)? You might've noticed that I've been using that commit message syntax since march 2023 for all of my commits in SecLists.
> 
> The conventional commits syntax allows for automation to batch-process commits based on their commit messages. The standardised syntax allows for scripts to easily differentiate between commits that add **features** and commits that **fix** issues in a given project. It also allows for distinctions between which **components** of a project have been affected by any given commit.
> 
> What's more, Conventional Commits allow developers to save precious time when writing the changelogs for a new project version. A simple alphabetical sort of all commit messages is enough to get an ordered list of the new features and fixes, grouped together by the project component that they affect.
> 
> Does that sound good? I could make another new pull request and add a note about using Conventional Commits to the CONTRIBUTING.md if you agree that it could be useful for the project.
> 
> Cheers.

Note: If we do implement conventional commits, explanations for when to use each commit "type" (`feat`, `fix` and `chore`) should be added, along with a list of which "components" are used in this repository, for example: `wordlist`, `cicd`, `docs`, etc.

**Comment by g0tmi1k** [comment]
Hello @ItsIgnacioPortal 

Thanks for taking the time to create the MR as well as making it detailed :)

I know @danielmiessler and @jhaddix in recent years haven't been able to put in much time (I saw @danielmiessler commit the not too long ago?).
Im not sure what is currently the best way to reach them - tagging them in here, so hopefully they reply!

With regards to conventional commits, Im aware of it and all for it.
My only thing would be "enforcing it". We can recommend/encouraged it, but wouldn't want it to be a hard requirement (I don't want to discourage people by making them jump though more hops).

**Pull request merged**
