### PR TITLE
Create CommonAdminBase64.txt

### PR DESCRIPTION
**Pull request by xrobhal**
Common administrator usernames encoded into ASCII Base64 strings.

### CODE REVIEW

**Comment by g0tmi1k** [comment]
What is the source of this?

Could also the format be:
```
<username>:<password>
administrator:YWRtaW5pc3RyYXRvcg==
```

**Comment by xrobhal** [comment]
Updated format - new commit. Some CTF web applications encode usernames using Base64, the suggested list could be used to fuzz the encoded usernames.

**Comment by g0tmi1k** [comment]
But where did you get the values from before? Do you have a link?

**Comment by xrobhal** [comment]
https://github.com/danielmiessler/SecLists/blob/master/Usernames/top-usernames-shortlist.txt 

Adjusted some capitalisation and encoded to Base64. This isn't a new list, I've just encoded an existing one for ease of use.

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
