### PR TITLE
add 7-digits-0000000-9999999 to Fuzzing

### PR DESCRIPTION
**Pull request by iMaz1n**

### CODE REVIEW

**Comment by drwetter** [comment]
I would rather suggest not to merge this. Every tester understand the job should be able to generate this by her/himself. It clogs diskspace around the world.

**Comment by mazen160** [comment]
```shell
$ crunch 7 7 0123456789 > words.txt
```
Should be safer in term of space to use within the repository.

**Comment by drwetter** [comment]
or ``prompt>  for i in {0000000..9999999}; do echo $i;  done >7-digits-0000000-9999999.txt ``

Also e.g. the existing file like ``6-digits-000000-999999.txt`` is just futile (other than resistance ;-)  )

**Comment by g0tmi1k** [comment]
Thanks for the suggestion, but I do agree with the comments

**Pull request closed without merging**
