### PR TITLE
+5 payloads, some enhancements

### PR DESCRIPTION
**Pull request by s0md3v**
- Added 5 new payloads
- Changed an occurrence of `&` to `%26` to make it URL safe
- Randomized cases of all tags and attributes for bypassing case sensitive filters

### CODE REVIEW

**Comment by g0tmi1k** [comment]
@s0md3v any input on this?

**Comment by s0md3v** [comment]
I am not sure what input you are expecting on this.
I just did some additions and enhancements to the payload list that I contributed earlier.

**Comment by g0tmi1k** [comment]
As stated in the review:

```
Why is it now Z not x?
Before: <x oncut=alert()>x
After: <Z oncut=alert()>x
```

```
Is "click here" needed? None of the others have it.
<D3/OnpOinTeReENer=confirm``>click here
```

**Comment by s0md3v** [comment]
`Z` and `x` are both valid and don't affect the functionality of the payload. I was just randomly changing cases of the payloads (`body` -> `boDY`) for filter evasion and I might have typed `Z` instead of `X` but it's alright.

No, `click here` isn't needed. It just needs to be a string.

**Comment by g0tmi1k** [comment]
Thanks! Mierged

**Pull request merged**
