### PR TITLE
Structure Clean Up

### PR DESCRIPTION
**Pull request by g0tmi1k**
A bit of file organization and re-structuring

### CODE REVIEW

**Comment by g0tmi1k** [comment]
If possible, could there be a tag'd release afterwards?

**Comment by g0tmi1k** [comment]
Fix merge conflict

**Comment by jhaddix** [comment]
@danielmiessler reviewed. Looks good to me, ready to merge with your approval.

**Comment by g0tmi1k** [comment]
Fix merge conflict once more.

**Comment by g0tmi1k** [comment]
🎉🎈  🎉🎈  🎉
❤️ 😍 👍 
🎉🎈  🎉🎈  🎉


THANK YOU! 😃

**Pull request merged**
