### PR TITLE
Rename lang-french.txt to lang-french-full.txt

### PR DESCRIPTION
**Pull request by clem9669**
Adding the full french dictionary.

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Hello,

Thanks for the suggestion - whats the source on this?

**Comment by clem9669** [comment]
See the following for the source : 
> https://www.pallier.org/liste-de-mots-francais.html (website for download)
> http://www.fifi.org/doc/ifrench-gut/fr/reference.pdf.gz (paper for the french dictionary generation)

The downloadable *https://www.pallier.org/extra/liste.de.mots.francais.frgut.txt* is a liste de 336531 mots du français (encodés en utf-8).

**Comment by clem9669** [comment]
From 392 to 336531 words. It will be a way better dictionary but not efficient at all for brute-forcing

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
