### PR TITLE
Added top 100 email domains to Seclists/Fuzzing

### PR DESCRIPTION
**Pull request by ipentest**
The file email-top-100-domains.txt has been added to the path SecLists/Fuzzing

Thanks,
ipentest

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Where did this list come from? Whats the source?

**Comment by CoccodrillooXDS** [comment]
@g0tmi1k I think it is from [here](https://email-verify.my-addr.com/list-of-most-popular-email-domains.php)

**Comment by g0tmi1k** [comment]
Thanks @ipentest 

And cheers @CoccodrillooXDS !

**Comment by CoccodrillooXDS** [comment]
No problem :D

**Pull request merged**
