### PR TITLE
Create seasons.txt

### PR DESCRIPTION
**Pull request by 5tr1x**
password permutations of seasons

### CODE REVIEW

**Comment by PinkDev1** [comment]
Very cool! How did you generate the permutations?

**Comment by 5tr1x** [comment]
Combination of hashcat rules and a little bash
-------- Original message --------From: PinkDev1 ***@***.***> Date: 12/17/21  7:42 PM  (GMT-06:00) To: danielmiessler/SecLists ***@***.***> Cc: 5tr1x ***@***.***>, Author ***@***.***> Subject: Re: [danielmiessler/SecLists] Create seasons.txt (PR #679) 
Very cool! How did you generate the permutations?

**Comment by PinkDev1** [comment]
Now that I look at it, I think it'll be better if year permutations are not included on the list, as that makes this list require maintenance, and also extends it for no good reason. If anyone uses this list, they'll have to concatenate the year string themselves.

**Comment by PinkDev1** [comment]
Also I was asking _**EXACTLY**_ how you generated the permutations. (ie. With what script?) Maybe there is a way to generate even more permutations.

**Comment by 5tr1x** [comment]
Ah yes the year thing makes sense. And you can check out the script I used under my repo - misc bash I think :)
-------- Original message --------From: PinkDev1 ***@***.***> Date: 12/19/21  6:08 PM  (GMT-06:00) To: danielmiessler/SecLists ***@***.***> Cc: 5tr1x ***@***.***>, Author ***@***.***> Subject: Re: [danielmiessler/SecLists] Create seasons.txt (PR #679) 
Also I was asking EXACTLY how you generated the permutations. (ie. With what script?) Maybe there is a way to generate even more permutations.

**Comment by g0tmi1k** [comment]
Is this the script? 

```
for i in `cat $1`; do echo ${i}; echo ${i}2019; echo ${i}2020; echo ${i}2021; echo ${i}2022; echo ${i}1; echo ${i}123; done >> n
for i in `cat n`; do echo ${i}; echo ${i}'!'; echo ${i}'@'; echo ${i}'#'; echo ${i}'$'; echo ${i}'%'; echo ${i}'^'; echo ${i}'&'; echo ${i}'*'; echo ${i}'?'; done >> s
hashcat s -r /usr/share/hashcat/rules/leetspeak.rule --stdout > hc
wordlister --input s --perm 1 --min 4 --max 48 --leet &>/dev/null
mv output.txt wl
cat hc wl | sort -u > vvv
wordlister --input vvv --perm 1 --min 4 --max 48 --cap --up &>/dev/null
cat output.txt | sort -u > $2
rm n s hc wl vvv output.txt
```

https://github.com/5tr1x/misc_bash/blob/main/create-wordlist.sh

If so, it doesn't have a input wordlist (reads argument one), what was the base input file?

**Comment by 5tr1x** [comment]
Yes, that's the script. The input file was just a list of seasons in lowercase:

spring
summer
autumn
fall
winter

**Comment by g0tmi1k** [comment]
Thank you!

**Pull request merged**
